spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <your github client id>
            clientSecret: <your github client secret>
          google:
            client-id: <your google client id>
            client-secret: <your google client secret>